### ISSUE TITLE
(Mix) Could not compile dependency :credentials_obfuscation, "escript.exe

### ISSUE THREAD

**Issue by SyedMuzamilM** [rabbitmq/credentials-obfuscation#11]
While compiling my project. I am getting this error:

`
(Mix) Could not compile dependency :credentials_obfuscation, "escript.exe "c:/Users/Syed Muzamil/.mix/rebar3" bare compile --paths="f:/projects_startup/dogehouse/kousa/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile credentials_obfuscation", update it with "mix deps.update credentials_obfuscation" or clean it with "mix deps.clean credentials_obfuscation"
`

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
