### ISSUE TITLE
Remove rebar3_hex plugin from rebar.config

### ISSUE THREAD

**Issue by newmanjeff** [rabbitmq/credentials-obfuscation#22]
rebar3_hex should not be included as a plugin in rebar.config.  See [documenation](https://hexdocs.pm/rebar3_hex/readme.html#setup):

> NOTE : Be sure not to add rebar3_hex to the plugins section within a projects rebar3 config as this will become a dependency for others downloading your package from hex.pm

Perhaps it should be in `project_plugins` instead.

**Comment by michaelklishin** [comment]
Please submit a PR?

**Comment by newmanjeff** [comment]
Done.
