### ISSUE TITLE
Add cuttlefish schema

### ISSUE THREAD

**Issue by SimonUnge** [rabbitmq/credentials-obfuscation#28]
### Is your feature request related to a problem? Please describe.

I would like to add a cuttlefish schema file for the credentials_obfuscation application env (`enabled` `cipher` `hash` `iterations`) so it be easier to config that config in say rabbitmq without using advanced config.

### Describe the solution you'd like

Just add the schema file under `priv/schema` and leave it at that, and let whatever app that uses it look there (such as rabbitmq)

**Comment by michaelklishin** [comment]
@SimonUnge sounds good

**Comment by michaelklishin** [comment]
``` ini
credentials_obfuscation.enabled = true
credentials_obfuscation.cipher = aes_cbc256
credentials_obfuscation.hash = sha512
credentials_obfuscation.iterations = 500
```

Something like this seems reasonable to me.

**Comment by SimonUnge** [comment]
> ```ini
> credentials_obfuscation.enabled = true
> credentials_obfuscation.cipher = aes_cbc256
> credentials_obfuscation.hash = sha512
> credentials_obfuscation.iterations = 500
> ```
> 
> Something like this seems reasonable to me.

Just to be clear, you mean reasonable _defaults_ right @michaelklishin
